#Configuración de Vagrant donde nos piden que creemos tres maquinas virtuales un hostA,hostB,hostC que esten conectadas entre sí
#Para ello les he puesto a cada host una dirección estática dentro de una misma red para que puedan verse las unas con las otras. 


			Vagrant.configure("2") do |config|
			config.vm.define "hostC" do |hostC|
							hostC.vm.box="techchad2022/ubuntu2204"
							hostC.vm.network "private_network", ip:"192.168.10.13"
							hostC.vm.hostname = "hostC"
							hostC.vm.provision "shell", inline: <<-SHELL 
									apt-get install -y tar.gz
									apt-get install -y restic
								SHELL
			
				end
				
				config.vm.define "hostB" do |hostB|
				hostB.vm.box="techchad2022/ubuntu2204"
				hostB.vm.network "private_network", ip:"192.168.10.12"
				hostB.vm.hostname = "hostB"
				hostB.vm.provision "shell", inline: <<-SHELL 
						apt-get install -y rsync
						apt-get install -y tar.gz
						apt-get install -y restic
						SHELL
				
				end
				
				config.vm.define "hostA" do |hostA|
						hostA.vm.box = "techchad2022/ubuntu2204"
						hostA.vm.network "private_network", ip:"192.168.10.11"
						hostA.vm.hostname = "hostA"
						hostA.vm.provision "shell", inline: <<-SHELL
							echo '0 12 * * * backup.sh' | crontab -
							echo '0 12 * * * restic.sh' | crontab -
							apt-get install -y rsync
							apt-get install -y restic
							apt-get install -y tar.gz
							useradd -m luis 
							useradd -m pedro
							useradd -m juan 
							mkdir -p /home/luis/Clientes
							chmod 755 /home/luis/Clientes
							chown juan:pedro /home/luis/Clientes
							
						SHELL
						
						hostA.vm.provision "shell", path: "backup.sh", privileged: true, run: "always"
						hostA.vm.provision "shell", path: "restic.sh", privileged: true, run: "always"
				end
			end