Vagrant.configure("2") do |config|

  config.vm.define :cliente4 do |cliente4|
    cliente4.vm.box = "gusztavvargadr/ubuntu-desktop"
    cliente4.vm.network "private_network", ip: "172.16.3.11", virtualbox__intnet: "ZonaControlada"
	
	#Añado la ruta por defecto para que tenga la salida por el firewall
    cliente4.vm.provision "shell", inline: <<-SHELL
	  #Añado la ruta por defecto para que tenga la salida por el firewall
      ip route add default via 172.16.3.254 dev eth1
      apt-get update

    SHELL
  end

   
  config.vm.define :cliente5 do |cliente5|
    cliente5.vm.box = "techchad2022/ubuntu2204"
    cliente5.vm.network "private_network", virtualbox__intnet: "ZonaControlada",type: "dhcp"
	
   #instalamos iptables y curl para posteriormente instalar docker y crear el contenedor nginx que mostrará mi nombre y apellidos
   cliente5.vm.provision "shell", inline: <<-SHELL
      ip route add default via 172.16.3.254 dev eth1
      apt-get update
      apt-get install -y iptables 
	  apt-get install -y curl
	  curl -fsSL https://get.docker.com -o get-docker.sh 
	  sh get-docker.sh 
	  groupadd docker 
	  usermod -aG docker vagrant 
	  newgrp docker
      docker run -it --rm -d -p 8080:80 --name webNginx -v ~/nginx:/usr/share/nginx/html nginx
      echo "Jose Manuel Rivera Boza" > ~/nginx/index.html
    SHELL
  end

  config.vm.define :cliente6 do |cliente6|
    cliente6.vm.box = "techchad2022/ubuntu2204"
    cliente6.vm.network "private_network", virtualbox__intnet: "ZonaControlada",type: 'dhcp'
	#Instalamos en este cliente las herramientas curl y wget 
    cliente6.vm.provision "shell", inline: <<-SHELL
      ip route add default via 172.16.3.254 dev eth1
      apt-get update
      apt-get install -y curl
	  apt-get install -y wget
    SHELL
  end
end
