Vagrant.configure("2") do |config|
  config.vm.box = "techchad2022/ubuntu2204"
  config.vm.network "public_network"
  config.vm.synced_folder "./", "/sincronizada"
   #Instalamos docker compose,y como tenemos sincronizada un directorio entre el host y la máquina virtual utilizamos el docker-compose.yml para levantar el contenedor wireguard
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y docker-compose
     cp /sincronizada/docker-compose.yml /home/vagrant/
     docker-compose up -d
   SHELL
end

