Vagrant.configure("2") do |config|
	config.vm.define "hostA" do |hostA|
		hostA.vm.box= "techchad2022/ubuntu2204"
		hostA.vm.network "private_network", type: "dhcp"
		hostA.vm.provision "shell", path: "ACL.sh" , privileged:true
		hostA.vm.provision "shell", inline: <<-SHELL 
			apt-get install -y tar.gz
			
		SHELL
	end
end
